export enum GraphQLErrorCode {
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    PARTICIPANT_UNAUTHORIZED = "PARTICIPANT_UNAUTHORIZED",
    GAME_UNAVAILABLE = "GAME_UNAVAILABLE",
    ALREADY_JOINED = "ALREADY_JOINED",
    NOT_FOUND = "NOT_FOUND",
}
