"""init models

Revision ID: 28a7db76fdb0
Revises: 4ee3097c7f28
Create Date: 2025-09-06 15:04:11.339516

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '28a7db76fdb0'
down_revision: Union[str, Sequence[str], None] = '4ee3097c7f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('years', sa.ARRAY(sa.Integer()), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('code', sa.UUID(as_uuid=False), nullable=False),
                    sa.Column('status', sa.Enum('in_lobby', 'in_progress', 'ended', name='gamestatusenum'),
                              nullable=False),
                    sa.Column('game_setting_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['game_setting_id'], ['game_settings.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('game_participations',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('leader', sa.Boolean(), nullable=False),
                    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('game_turns',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('status',
                              sa.Enum('not_started', 'generating', 'waiting_for_answers', 'answered', 'confirmed',
                                      name='turnstatusenum'), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('game_id', 'index', name='uq_turn_game_index')
                    )
    op.create_table('game_questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('participation_id', sa.Integer(), nullable=False),
                    sa.Column('turn_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.ForeignKeyConstraint(['participation_id'], ['game_participations.id'], ),
                    sa.ForeignKeyConstraint(['turn_id'], ['game_turns.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('game_results',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('participation_id', sa.Integer(), nullable=False),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.ForeignKeyConstraint(['participation_id'], ['game_participations.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('game_id', 'participation_id', name='uq_result_game_participation')
                    )
    op.create_table('game_choices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('game_question_id', sa.Integer(), nullable=False),
                    sa.Column('chosen', sa.Boolean(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('result', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['game_question_id'], ['game_questions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_choices')
    op.drop_table('game_results')
    op.drop_table('game_questions')
    op.drop_table('game_turns')
    op.drop_table('game_participations')
    op.drop_table('games')
    op.drop_table('game_settings')
    # ### end Alembic commands ###
