"""empty message

Revision ID: 44e814c98b9f
Revises: e2d099f624ca
Create Date: 2025-12-03 09:28:55.084571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e814c98b9f'
down_revision: Union[str, Sequence[str], None] = 'e2d099f624ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_choices', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_choices', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
