"""add count_confirmed column to game_turn

Revision ID: 4b51f56ce1f4
Revises: 6af2146f611f
Create Date: 2025-09-06 22:59:30.858944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b51f56ce1f4'
down_revision: Union[str, Sequence[str], None] = '6af2146f611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_turns', sa.Column('count_confirmed', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_turns', 'count_confirmed')
    # ### end Alembic commands ###
