"""change_type_of_oauth_provider

Revision ID: 4ee3097c7f28
Revises: c46119e10a8c
Create Date: 2025-09-05 15:48:48.575295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee3097c7f28'
down_revision: Union[str, Sequence[str], None] = 'c46119e10a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    oauth_provider_enum = sa.Enum('GOOGLE', name='oauthprovider')
    op.execute("""
        UPDATE users
        SET oauth_provider = 'GOOGLE'
        WHERE oauth_provider IS NOT NULL
          AND oauth_provider NOT IN ('GOOGLE')
    """)

    oauth_provider_enum.create(op.get_bind(), checkfirst=True)

    # меняем колонку, чтобы использовать enum
    op.alter_column(
        'users',
        'oauth_provider',
        existing_type=sa.VARCHAR(length=50),
        type_=oauth_provider_enum,
        existing_nullable=True,
        postgresql_using='oauth_provider::oauthprovider'
    )
    op.create_index('idx_email_provider', 'users', ['email', 'oauth_provider', 'oauth_id'], unique=True)
    op.create_index('uq_oauth_provider_id', 'users', ['oauth_provider', 'oauth_id'], unique=True, postgresql_where=sa.text('oauth_provider IS NOT NULL AND oauth_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_oauth_provider_id', table_name='users', postgresql_where=sa.text('oauth_provider IS NOT NULL AND oauth_id IS NOT NULL'))
    op.drop_index('idx_email_provider', table_name='users')
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.Enum('GOOGLE', name='oauthprovider'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
