"""replace count_confirmed with confirmed_by list

Revision ID: 58ecf58b0212
Revises: 4b51f56ce1f4
Create Date: 2025-09-06 23:08:12.592386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ecf58b0212'
down_revision: Union[str, Sequence[str], None] = '4b51f56ce1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_turns', sa.Column('confirmed_by', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.drop_column('game_turns', 'count_confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_turns', sa.Column('count_confirmed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('game_turns', 'confirmed_by')
    # ### end Alembic commands ###
