"""add title_for_everyone field to game_choices

Revision ID: 9190c44590a5
Revises: 28a7db76fdb0
Create Date: 2025-09-06 15:55:58.472136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9190c44590a5'
down_revision: Union[str, Sequence[str], None] = '28a7db76fdb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_choices', sa.Column('title_for_everyone', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_choices', 'title_for_everyone')
    # ### end Alembic commands ###
