"""TEMP: deleted confirmed_by

Revision ID: afe1d219a9b3
Revises: 58ecf58b0212
Create Date: 2025-09-06 23:43:17.868819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe1d219a9b3'
down_revision: Union[str, Sequence[str], None] = '58ecf58b0212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_turns', 'confirmed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_turns', sa.Column('confirmed_by', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
