"""added game status

Revision ID: c1da003fa1a8
Revises: 9190c44590a5
Create Date: 2025-09-06 16:05:28.785740

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1da003fa1a8'
down_revision: Union[str, Sequence[str], None] = '9190c44590a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE gamestatusenum ADD VALUE IF NOT EXISTS 'generating_results';")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
