"""returned confirmed_by

Revision ID: db91112b57ac
Revises: afe1d219a9b3
Create Date: 2025-09-06 23:44:00.482468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db91112b57ac'
down_revision: Union[str, Sequence[str], None] = 'afe1d219a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_turns', sa.Column('confirmed_by', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_turns', 'confirmed_by')
    # ### end Alembic commands ###
