"""added game settings seeding

Revision ID: e57bda582deb
Revises: c1da003fa1a8
Create Date: 2025-09-06 19:12:57.282762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57bda582deb'
down_revision: Union[str, Sequence[str], None] = 'c1da003fa1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_choices', sa.Column('result_tags', sa.ARRAY(sa.Integer()), nullable=False))
    op.alter_column('game_choices', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('game_choices', 'result',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('game_results', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('game_results', 'title')
    op.execute("""INSERT INTO game_settings (years) VALUES (ARRAY[12, 15, 18, 20, 22, 25, 28, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])""")
    op.execute("""INSERT INTO game_settings (years) VALUES (ARRAY[12, 14, 16, 17, 18, 20, 22, 24, 26, 28, 30, 35, 40, 45, 50, 55, 60, 65, 70])""")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_results', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('game_results', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('game_choices', 'result',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('game_choices', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('game_choices', 'result_tags')
    # ### end Alembic commands ###
